name: gg_value
description: GgValue allows managing a value in a dart application. It provides a stream, a flag preventing too many updates, and a custom transform and a comparison function.
version: 1.6.0
homepage: https://github.com/inlavigo/gg_value
repository: https://github.com/inlavigo/gg_value

environment:
  sdk: ">=3.2.0 <4.0.0"

dev_dependencies:
  fake_async: ^1.1.0
  test: ^1.16.6
  flutter_lints: ^3.0.1
  args: ^2.4.2
  pana: ^0.22.2
  gg_capture_print: ^1.0.2
  gg_install_gg: ^1.0.1
